/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-09-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Payment method for card emi
*/
export class CardEMI {
    /**
    * The channel for card payments will always be \"link\"
    */
    'channel'?: string;
    /**
    * Customer card number.
    */
    'cardNumber'?: string;
    /**
    * Customer name mentioned on the card.
    */
    'cardHolderName'?: string;
    /**
    * Card expiry month.
    */
    'cardExpiryMm'?: string;
    /**
    * Card expiry year.
    */
    'cardExpiryYy'?: string;
    /**
    * CVV mentioned on the card.
    */
    'cardCvv'?: string;
    /**
    * Card alias as returned by Cashfree Vault API
    */
    'cardAlias'?: string;
    /**
    * Card bank name, required for EMI payments. This is the bank user has selected for EMI. One of [\"hdfc, \"kotak\", \"icici\", \"rbl\", \"bob\", \"standard chartered\", \"axis\", \"au\", \"yes\", \"sbi\", \"fed\", \"hsbc\", \"citi\", \"amex\"]
    */
    'cardBankName'?: CardEMI.CardBankNameEnum;
    /**
    * EMI tenure selected by the user
    */
    'emiTenure'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "string"
        },
        {
            "name": "cardNumber",
            "baseName": "card_number",
            "type": "string"
        },
        {
            "name": "cardHolderName",
            "baseName": "card_holder_name",
            "type": "string"
        },
        {
            "name": "cardExpiryMm",
            "baseName": "card_expiry_mm",
            "type": "string"
        },
        {
            "name": "cardExpiryYy",
            "baseName": "card_expiry_yy",
            "type": "string"
        },
        {
            "name": "cardCvv",
            "baseName": "card_cvv",
            "type": "string"
        },
        {
            "name": "cardAlias",
            "baseName": "card_alias",
            "type": "string"
        },
        {
            "name": "cardBankName",
            "baseName": "card_bank_name",
            "type": "CardEMI.CardBankNameEnum"
        },
        {
            "name": "emiTenure",
            "baseName": "emi_tenure",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CardEMI.attributeTypeMap;
    }
}

export namespace CardEMI {
    export enum CardBankNameEnum {
        Hdfc = <any> 'hdfc',
        Kotak = <any> 'kotak',
        Icici = <any> 'icici',
        Rbl = <any> 'rbl',
        Bob = <any> 'bob',
        StandardChartered = <any> 'standard chartered',
        Axis = <any> 'axis',
        Au = <any> 'au',
        Yes = <any> 'yes',
        Sbi = <any> 'sbi',
        Fed = <any> 'fed',
        Hsbc = <any> 'hsbc',
        Citi = <any> 'citi',
        Amex = <any> 'amex'
    }
}
