/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-09-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Details of the customer for whom eligibility is being checked.
*/
export class CustomerDetailsCardlessEMI {
    /**
    * Phone Number of the customer
    */
    'customerPhone': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "customerPhone",
            "baseName": "customer_phone",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerDetailsCardlessEMI.attributeTypeMap;
    }
}

