/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-09-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CardOffer } from './cardOffer';
import { EMIOffer } from './eMIOffer';
import { OfferAll } from './offerAll';
import { OfferCard } from './offerCard';
import { OfferEMI } from './offerEMI';
import { OfferNB } from './offerNB';
import { OfferNBNetbanking } from './offerNBNetbanking';
import { OfferPaylater } from './offerPaylater';
import { OfferUPI } from './offerUPI';
import { OfferWallet } from './offerWallet';
import { PaylaterOffer } from './paylaterOffer';
import { WalletOffer } from './walletOffer';

export class OfferValidationsPaymentMethod {
    /**
    * All offers applicable
    */
    'all': object;
    'card': CardOffer;
    'netbanking': OfferNBNetbanking;
    'app'?: WalletOffer;
    'upi': object;
    'paylater': PaylaterOffer;
    'emi': EMIOffer;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "all",
            "baseName": "all",
            "type": "object"
        },
        {
            "name": "card",
            "baseName": "card",
            "type": "CardOffer"
        },
        {
            "name": "netbanking",
            "baseName": "netbanking",
            "type": "OfferNBNetbanking"
        },
        {
            "name": "app",
            "baseName": "app",
            "type": "WalletOffer"
        },
        {
            "name": "upi",
            "baseName": "upi",
            "type": "object"
        },
        {
            "name": "paylater",
            "baseName": "paylater",
            "type": "PaylaterOffer"
        },
        {
            "name": "emi",
            "baseName": "emi",
            "type": "EMIOffer"
        }    ];

    static getAttributeTypeMap() {
        return OfferValidationsPaymentMethod.attributeTypeMap;
    }
}

