/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-09-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Offer meta details object
*/
export class OfferMeta {
    /**
    * Title for the Offer.
    */
    'offerTitle': string;
    /**
    * Description for the Offer.
    */
    'offerDescription': string;
    /**
    * Unique identifier for the Offer.
    */
    'offerCode': string;
    /**
    * Start Time for the Offer
    */
    'offerStartTime': string;
    /**
    * Expiry Time for the Offer
    */
    'offerEndTime': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "offerTitle",
            "baseName": "offer_title",
            "type": "string"
        },
        {
            "name": "offerDescription",
            "baseName": "offer_description",
            "type": "string"
        },
        {
            "name": "offerCode",
            "baseName": "offer_code",
            "type": "string"
        },
        {
            "name": "offerStartTime",
            "baseName": "offer_start_time",
            "type": "string"
        },
        {
            "name": "offerEndTime",
            "baseName": "offer_end_time",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OfferMeta.attributeTypeMap;
    }
}

