/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-09-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Settlement entity object
*/
export class SettlementsEntity {
    'cfPaymentId'?: number;
    'cfSettlementId'?: number;
    'settlementCurrency'?: string;
    'orderId'?: string;
    'entity'?: string;
    'orderAmount'?: number;
    'paymentTime'?: string;
    'serviceCharge'?: number;
    'serviceTax'?: number;
    'settlementAmount'?: number;
    'settlementId'?: number;
    'transferId'?: number;
    'transferTime'?: string;
    'transferUtr'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cfPaymentId",
            "baseName": "cf_payment_id",
            "type": "number"
        },
        {
            "name": "cfSettlementId",
            "baseName": "cf_settlement_id",
            "type": "number"
        },
        {
            "name": "settlementCurrency",
            "baseName": "settlement_currency",
            "type": "string"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        },
        {
            "name": "entity",
            "baseName": "entity",
            "type": "string"
        },
        {
            "name": "orderAmount",
            "baseName": "order_amount",
            "type": "number"
        },
        {
            "name": "paymentTime",
            "baseName": "payment_time",
            "type": "string"
        },
        {
            "name": "serviceCharge",
            "baseName": "service_charge",
            "type": "number"
        },
        {
            "name": "serviceTax",
            "baseName": "service_tax",
            "type": "number"
        },
        {
            "name": "settlementAmount",
            "baseName": "settlement_amount",
            "type": "number"
        },
        {
            "name": "settlementId",
            "baseName": "settlement_id",
            "type": "number"
        },
        {
            "name": "transferId",
            "baseName": "transfer_id",
            "type": "number"
        },
        {
            "name": "transferTime",
            "baseName": "transfer_time",
            "type": "string"
        },
        {
            "name": "transferUtr",
            "baseName": "transfer_utr",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SettlementsEntity.attributeTypeMap;
    }
}

