/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-09-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Use to split order when cashfree\'s Easy Split is enabled for your account.
*/
export class VendorSplit {
    /**
    * Vendor id created in Cashfree system
    */
    'vendorId'?: string;
    /**
    * Amount which will be associated with this vendor
    */
    'amount'?: number;
    /**
    * Percentage of order amount which shall get added to vendor account
    */
    'percentage'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "vendorId",
            "baseName": "vendor_id",
            "type": "string"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "percentage",
            "baseName": "percentage",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return VendorSplit.attributeTypeMap;
    }
}

