/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Request to capture or void transaction
*/
export class AuthorizationRequest {
    /**
    * Type of authorization to run. Can be one of \'CAPTURE\' , \'VOID\'
    */
    'action'?: AuthorizationRequest.ActionEnum;
    /**
    * The amount if you are running a \'CAPTURE\'
    */
    'amount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "AuthorizationRequest.ActionEnum"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AuthorizationRequest.attributeTypeMap;
    }
}

export namespace AuthorizationRequest {
    export enum ActionEnum {
        Capture = <any> 'CAPTURE',
        Void = <any> 'VOID'
    }
}
