/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Request body for cardless emi payment method
*/
export class CardlessEMI {
    /**
    * The channel for cardless EMI is always `link`
    */
    'channel'?: string;
    /**
    * One of [`flexmoney`, `zestmoney`, `hdfc`, `icici`, `cashe`, `idfc`, `kotak`]
    */
    'provider'?: CardlessEMI.ProviderEnum;
    /**
    * Customers phone number for this payment instrument. If the customer is not eligible you will receive a 400 error with type as \'invalid_request_error\' and code as \'invalid_request_error\'
    */
    'phone'?: string;
    /**
    * EMI tenure for the selected provider. This is mandatory when provider is one of [`hdfc`, `icici`, `cashe`, `idfc`, `kotak`]
    */
    'emiTenure'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "string"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "CardlessEMI.ProviderEnum"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string"
        },
        {
            "name": "emiTenure",
            "baseName": "emi_tenure",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CardlessEMI.attributeTypeMap;
    }
}

export namespace CardlessEMI {
    export enum ProviderEnum {
        Flexmoney = <any> 'flexmoney',
        Zestmoney = <any> 'zestmoney',
        Hdfc = <any> 'hdfc',
        Icici = <any> 'icici',
        Cashe = <any> 'cashe',
        Idfc = <any> 'idfc',
        Kotak = <any> 'kotak'
    }
}
