/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { VendorSplit } from './vendorSplit';

/**
* create refund request object
*/
export class CreateRefundRequest {
    /**
    * Amount to be refunded. Should be lesser than or equal to the transaction amount. (Decimals allowed)
    */
    'refundAmount': number;
    /**
    * An unique ID to associate the refund with. Provie alphanumeric values
    */
    'refundId': string;
    /**
    * A refund note for your reference.
    */
    'refundNote'?: string;
    /**
    * Speed at which the refund is processed. It\'s an optional field with default being STANDARD
    */
    'refundSpeed'?: CreateRefundRequest.RefundSpeedEnum;
    'refundSplits'?: Array<VendorSplit>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "refundAmount",
            "baseName": "refund_amount",
            "type": "number"
        },
        {
            "name": "refundId",
            "baseName": "refund_id",
            "type": "string"
        },
        {
            "name": "refundNote",
            "baseName": "refund_note",
            "type": "string"
        },
        {
            "name": "refundSpeed",
            "baseName": "refund_speed",
            "type": "CreateRefundRequest.RefundSpeedEnum"
        },
        {
            "name": "refundSplits",
            "baseName": "refund_splits",
            "type": "Array<VendorSplit>"
        }    ];

    static getAttributeTypeMap() {
        return CreateRefundRequest.attributeTypeMap;
    }
}

export namespace CreateRefundRequest {
    export enum RefundSpeedEnum {
        Standard = <any> 'STANDARD',
        Instant = <any> 'INSTANT'
    }
}
