/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-09-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OfferDetails } from './offerDetails';
import { OfferMeta } from './offerMeta';
import { OfferTnc } from './offerTnc';
import { OfferValidations } from './offerValidations';

/**
* create offer backend request object
*/
export class CreateOfferBackendRequest {
    'offerMeta': OfferMeta;
    'offerTnc': OfferTnc;
    'offerDetails': OfferDetails;
    'offerValidations': OfferValidations;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "offerMeta",
            "baseName": "offer_meta",
            "type": "OfferMeta"
        },
        {
            "name": "offerTnc",
            "baseName": "offer_tnc",
            "type": "OfferTnc"
        },
        {
            "name": "offerDetails",
            "baseName": "offer_details",
            "type": "OfferDetails"
        },
        {
            "name": "offerValidations",
            "baseName": "offer_validations",
            "type": "OfferValidations"
        }    ];

    static getAttributeTypeMap() {
        return CreateOfferBackendRequest.attributeTypeMap;
    }
}

