/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Request body to create a terminal
*/
export class CreateTerminalRequest {
    /**
    * merchant’s internal terminal id
    */
    'terminalId'?: string;
    /**
    * terminal name to be assigned by merchants
    */
    'terminalName': string;
    /**
    * City where the terminal was created
    */
    'terminalArea'?: string;
    /**
    * additional note for terminal
    */
    'terminalNote'?: string;
    /**
    * phone number assigned to the terminal
    */
    'terminalPhoneNo': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "terminalId",
            "baseName": "terminal_id",
            "type": "string"
        },
        {
            "name": "terminalName",
            "baseName": "terminal_name",
            "type": "string"
        },
        {
            "name": "terminalArea",
            "baseName": "terminal_area",
            "type": "string"
        },
        {
            "name": "terminalNote",
            "baseName": "terminal_note",
            "type": "string"
        },
        {
            "name": "terminalPhoneNo",
            "baseName": "terminal_phone_no",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateTerminalRequest.attributeTypeMap;
    }
}

