/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CardlessEMIQueries } from './cardlessEMIQueries';

/**
* eligibilty request for cardless
*/
export class EligibilityCardlessEMIRequest {
    'queries': CardlessEMIQueries;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "queries",
            "baseName": "queries",
            "type": "CardlessEMIQueries"
        }    ];

    static getAttributeTypeMap() {
        return EligibilityCardlessEMIRequest.attributeTypeMap;
    }
}

