/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class EMIOffer {
    /**
    * Type of emi offer. Possible values are `credit_card_emi`, `debit_card_emi`, `cardless_emi`
    */
    'type': string;
    /**
    * Bank Name
    */
    'issuer': string;
    'tenures': Array<number>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "issuer",
            "baseName": "issuer",
            "type": "string"
        },
        {
            "name": "tenures",
            "baseName": "tenures",
            "type": "Array<number>"
        }    ];

    static getAttributeTypeMap() {
        return EMIOffer.attributeTypeMap;
    }
}

