/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The error details are present only for failed payments
*/
export class ErrorDetailsInPaymentsEntity {
    'errorCode'?: string;
    'errorDescription'?: string;
    'errorReason'?: string;
    'errorSource'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errorCode",
            "baseName": "error_code",
            "type": "string"
        },
        {
            "name": "errorDescription",
            "baseName": "error_description",
            "type": "string"
        },
        {
            "name": "errorReason",
            "baseName": "error_reason",
            "type": "string"
        },
        {
            "name": "errorSource",
            "baseName": "error_source",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ErrorDetailsInPaymentsEntity.attributeTypeMap;
    }
}

