/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Specify either the Settlement ID, Settlement UTR, or start date and end date to fetch the settlement details.
*/
export class FetchSettlementReconRequestFilters {
    /**
    * List of settlement IDs for which you want the settlement reconciliation details.
    */
    'cfSettlementIds'?: Array<number>;
    /**
    * List of settlement UTRs for which you want the settlement reconciliation details.
    */
    'settlementUtrs'?: Array<string>;
    /**
    * Specify the start date from when you want the settlement reconciliation details.
    */
    'startDate'?: string;
    /**
    * Specify the end date till when you want the settlement reconciliation details.
    */
    'endDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cfSettlementIds",
            "baseName": "cf_settlement_ids",
            "type": "Array<number>"
        },
        {
            "name": "settlementUtrs",
            "baseName": "settlement_utrs",
            "type": "Array<string>"
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "end_date",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FetchSettlementReconRequestFilters.attributeTypeMap;
    }
}

