/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FetchSettlementReconDataInner {
    /**
    * Unique ID associated with the event.
    */
    'eventId'?: string;
    /**
    * The event type can be PAYMENT, REFUND, REFUND_REVERSAL, DISPUTE, DISPUTE_REVERSAL, CHARGEBACK, CHARGEBACK_REVERSAL, OTHER_ADJUSTMENT.
    */
    'eventType'?: string;
    /**
    * Amount that is part of the settlement corresponding to the event.
    */
    'eventSettlementAmount'?: number;
    /**
    * Amount corresponding to the event. Example, refund amount, dispute amount, payment amount, etc.
    */
    'eventAmount'?: number;
    /**
    * Indicates if it is CREDIT/DEBIT sale.
    */
    'saleType'?: string;
    /**
    * Status of the event. Example - SUCCESS, FAILED, PENDING, CANCELLED.
    */
    'eventStatus'?: string;
    /**
    * Recon
    */
    'entity'?: string;
    /**
    * Time associated with the event. Example, transaction time, dispute initiation time
    */
    'eventTime'?: string;
    /**
    * Curreny type - INR.
    */
    'eventCurrency'?: string;
    /**
    * Unique order ID. Alphanumeric and only \'-\' and \'_\' allowed.
    */
    'orderId'?: string;
    /**
    * The amount which was passed at the order creation time.
    */
    'orderAmount'?: number;
    /**
    * Customer phone number.
    */
    'customerPhone'?: string;
    /**
    * Customer email.
    */
    'customerEmail'?: string;
    /**
    * Customer name.
    */
    'customerName'?: string;
    /**
    * Payment amount captured.
    */
    'paymentAmount'?: number;
    /**
    * Unique transaction reference number of the payment.
    */
    'paymentUtr'?: string;
    /**
    * Date and time when the payment was initiated.
    */
    'paymentTime'?: string;
    /**
    * Service charge applicable for the payment.
    */
    'paymentServiceCharge'?: number;
    /**
    * Service tax applicable on the payment.
    */
    'paymentServiceTax'?: number;
    /**
    * Cashfree Payments unique ID to identify a payment.
    */
    'cfPaymentId'?: number;
    /**
    * Unique ID to identify the settlement.
    */
    'cfSettlementId'?: number;
    /**
    * Date and time when the settlement was processed.
    */
    'settlementDate'?: string;
    /**
    * Unique transaction reference number of the settlement.
    */
    'settlementUtr'?: string;
    /**
    * Service charge that is applicable for splitting the payment.
    */
    'splitServiceCharge'?: number;
    /**
    * Service tax applicable for splitting the amount to vendors.
    */
    'splitServiceTax'?: number;
    /**
    * Vendor commission applicable for this transaction.
    */
    'vendorCommission'?: number;
    /**
    * Specifies whether the dispute was closed in favor of the merchant or customer. Possible values - Merchant, Customer.
    */
    'closedInFavorOf'?: string;
    /**
    * Date and time when the dispute was resolved.
    */
    'disputeResolvedOn'?: string;
    /**
    * Category of the dispute - Dispute code and the reason for dispute is shown.
    */
    'disputeCategory'?: string;
    /**
    * Note regarding the dispute.
    */
    'disputeNote'?: string;
    /**
    * Date and time when the refund was processed.
    */
    'refundProcessedAt'?: string;
    /**
    * The bank reference number for refund.
    */
    'refundArn'?: string;
    /**
    * A refund note for your reference.
    */
    'refundNote'?: string;
    /**
    * An unique ID associated with the refund.
    */
    'refundId'?: string;
    /**
    * Other adjustment remarks.
    */
    'adjustmentRemarks'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "eventId",
            "baseName": "event_id",
            "type": "string"
        },
        {
            "name": "eventType",
            "baseName": "event_type",
            "type": "string"
        },
        {
            "name": "eventSettlementAmount",
            "baseName": "event_settlement_amount",
            "type": "number"
        },
        {
            "name": "eventAmount",
            "baseName": "event_amount",
            "type": "number"
        },
        {
            "name": "saleType",
            "baseName": "sale_type",
            "type": "string"
        },
        {
            "name": "eventStatus",
            "baseName": "event_status",
            "type": "string"
        },
        {
            "name": "entity",
            "baseName": "entity",
            "type": "string"
        },
        {
            "name": "eventTime",
            "baseName": "event_time",
            "type": "string"
        },
        {
            "name": "eventCurrency",
            "baseName": "event_currency",
            "type": "string"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        },
        {
            "name": "orderAmount",
            "baseName": "order_amount",
            "type": "number"
        },
        {
            "name": "customerPhone",
            "baseName": "customer_phone",
            "type": "string"
        },
        {
            "name": "customerEmail",
            "baseName": "customer_email",
            "type": "string"
        },
        {
            "name": "customerName",
            "baseName": "customer_name",
            "type": "string"
        },
        {
            "name": "paymentAmount",
            "baseName": "payment_amount",
            "type": "number"
        },
        {
            "name": "paymentUtr",
            "baseName": "payment_utr",
            "type": "string"
        },
        {
            "name": "paymentTime",
            "baseName": "payment_time",
            "type": "string"
        },
        {
            "name": "paymentServiceCharge",
            "baseName": "payment_service_charge",
            "type": "number"
        },
        {
            "name": "paymentServiceTax",
            "baseName": "payment_service_tax",
            "type": "number"
        },
        {
            "name": "cfPaymentId",
            "baseName": "cf_payment_id",
            "type": "number"
        },
        {
            "name": "cfSettlementId",
            "baseName": "cf_settlement_id",
            "type": "number"
        },
        {
            "name": "settlementDate",
            "baseName": "settlement_date",
            "type": "string"
        },
        {
            "name": "settlementUtr",
            "baseName": "settlement_utr",
            "type": "string"
        },
        {
            "name": "splitServiceCharge",
            "baseName": "split_service_charge",
            "type": "number"
        },
        {
            "name": "splitServiceTax",
            "baseName": "split_service_tax",
            "type": "number"
        },
        {
            "name": "vendorCommission",
            "baseName": "vendor_commission",
            "type": "number"
        },
        {
            "name": "closedInFavorOf",
            "baseName": "closed_in_favor_of",
            "type": "string"
        },
        {
            "name": "disputeResolvedOn",
            "baseName": "dispute_resolved_on",
            "type": "string"
        },
        {
            "name": "disputeCategory",
            "baseName": "dispute_category",
            "type": "string"
        },
        {
            "name": "disputeNote",
            "baseName": "dispute_note",
            "type": "string"
        },
        {
            "name": "refundProcessedAt",
            "baseName": "refund_processed_at",
            "type": "string"
        },
        {
            "name": "refundArn",
            "baseName": "refund_arn",
            "type": "string"
        },
        {
            "name": "refundNote",
            "baseName": "refund_note",
            "type": "string"
        },
        {
            "name": "refundId",
            "baseName": "refund_id",
            "type": "string"
        },
        {
            "name": "adjustmentRemarks",
            "baseName": "adjustment_remarks",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FetchSettlementReconDataInner.attributeTypeMap;
    }
}

