/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LinkCustomerDetailsEntity } from './linkCustomerDetailsEntity';
import { LinkMetaEntity } from './linkMetaEntity';
import { LinkNotifyEntity } from './linkNotifyEntity';

/**
* Response when a payment link is cancelled
*/
export class LinkCancelledResponse {
    'cfLinkId'?: number;
    'linkId'?: string;
    'linkStatus'?: string;
    'linkCurrency'?: string;
    'linkAmount'?: number;
    'linkAmountPaid'?: number;
    'linkPartialPayments'?: boolean;
    'linkMinimumPartialAmount'?: number;
    'linkPurpose'?: string;
    'linkCreatedAt'?: string;
    'customerDetails'?: LinkCustomerDetailsEntity;
    'linkMeta'?: LinkMetaEntity;
    'linkUrl'?: string;
    'linkExpiryTime'?: string;
    /**
    * Key-value pair that can be used to store additional information about the entity. Maximum 5 key-value pairs
    */
    'linkNotes'?: { [key: string]: string; };
    'linkAutoReminders'?: boolean;
    'linkNotify'?: LinkNotifyEntity;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cfLinkId",
            "baseName": "cf_link_id",
            "type": "number"
        },
        {
            "name": "linkId",
            "baseName": "link_id",
            "type": "string"
        },
        {
            "name": "linkStatus",
            "baseName": "link_status",
            "type": "string"
        },
        {
            "name": "linkCurrency",
            "baseName": "link_currency",
            "type": "string"
        },
        {
            "name": "linkAmount",
            "baseName": "link_amount",
            "type": "number"
        },
        {
            "name": "linkAmountPaid",
            "baseName": "link_amount_paid",
            "type": "number"
        },
        {
            "name": "linkPartialPayments",
            "baseName": "link_partial_payments",
            "type": "boolean"
        },
        {
            "name": "linkMinimumPartialAmount",
            "baseName": "link_minimum_partial_amount",
            "type": "number"
        },
        {
            "name": "linkPurpose",
            "baseName": "link_purpose",
            "type": "string"
        },
        {
            "name": "linkCreatedAt",
            "baseName": "link_created_at",
            "type": "string"
        },
        {
            "name": "customerDetails",
            "baseName": "customer_details",
            "type": "LinkCustomerDetailsEntity"
        },
        {
            "name": "linkMeta",
            "baseName": "link_meta",
            "type": "LinkMetaEntity"
        },
        {
            "name": "linkUrl",
            "baseName": "link_url",
            "type": "string"
        },
        {
            "name": "linkExpiryTime",
            "baseName": "link_expiry_time",
            "type": "string"
        },
        {
            "name": "linkNotes",
            "baseName": "link_notes",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "linkAutoReminders",
            "baseName": "link_auto_reminders",
            "type": "boolean"
        },
        {
            "name": "linkNotify",
            "baseName": "link_notify",
            "type": "LinkNotifyEntity"
        }    ];

    static getAttributeTypeMap() {
        return LinkCancelledResponse.attributeTypeMap;
    }
}

