/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Netbanking payment method request body
*/
export class Netbanking {
    /**
    * The channel for netbanking will always be `link`
    */
    'channel': string;
    /**
    * Bank code
    */
    'netbankingBankCode'?: Netbanking.NetbankingBankCodeEnum;
    /**
    * String code for bank
    */
    'netbankingBankName'?: Netbanking.NetbankingBankNameEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "string"
        },
        {
            "name": "netbankingBankCode",
            "baseName": "netbanking_bank_code",
            "type": "Netbanking.NetbankingBankCodeEnum"
        },
        {
            "name": "netbankingBankName",
            "baseName": "netbanking_bank_name",
            "type": "Netbanking.NetbankingBankNameEnum"
        }    ];

    static getAttributeTypeMap() {
        return Netbanking.attributeTypeMap;
    }
}

