/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CashbackDetails } from './cashbackDetails';
import { DiscountDetails } from './discountDetails';

/**
* Offer details and type
*/
export class OfferDetails {
    /**
    * Offer Type for the Offer.
    */
    'offerType': OfferDetails.OfferTypeEnum;
    'discountDetails'?: DiscountDetails;
    'cashbackDetails'?: CashbackDetails;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "offerType",
            "baseName": "offer_type",
            "type": "OfferDetails.OfferTypeEnum"
        },
        {
            "name": "discountDetails",
            "baseName": "discount_details",
            "type": "DiscountDetails"
        },
        {
            "name": "cashbackDetails",
            "baseName": "cashback_details",
            "type": "CashbackDetails"
        }    ];

    static getAttributeTypeMap() {
        return OfferDetails.attributeTypeMap;
    }
}

export namespace OfferDetails {
    export enum OfferTypeEnum {
        Discount = <any> 'DISCOUNT',
        Cashback = <any> 'CASHBACK',
        DiscountAndCashback = <any> 'DISCOUNT_AND_CASHBACK',
        NoCostEmi = <any> 'NO_COST_EMI'
    }
}
