/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OfferType } from './offerType';

/**
* Filter for offers
*/
export class OfferFilters {
    /**
    * Array of offer_type to be filtered.
    */
    'offerType'?: Array<OfferType>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "offerType",
            "baseName": "offer_type",
            "type": "Array<OfferType>"
        }    ];

    static getAttributeTypeMap() {
        return OfferFilters.attributeTypeMap;
    }
}

