/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Offer terms and condition object
*/
export class OfferTnc {
    /**
    * TnC Type for the Offer. It can be either `text` or `link`
    */
    'offerTncType': OfferTnc.OfferTncTypeEnum;
    /**
    * TnC for the Offer.
    */
    'offerTncValue': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "offerTncType",
            "baseName": "offer_tnc_type",
            "type": "OfferTnc.OfferTncTypeEnum"
        },
        {
            "name": "offerTncValue",
            "baseName": "offer_tnc_value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OfferTnc.attributeTypeMap;
    }
}

export namespace OfferTnc {
    export enum OfferTncTypeEnum {
        Text = <any> 'text',
        Link = <any> 'link'
    }
}
