/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OfferValidationsPaymentMethod } from './offerValidationsPaymentMethod';

/**
* Offer validation object
*/
export class OfferValidations {
    /**
    * Minimum Amount for Offer to be Applicable
    */
    'minAmount'?: number;
    'paymentMethod': OfferValidationsPaymentMethod;
    /**
    * Maximum amount of Offer that can be availed.
    */
    'maxAllowed': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "minAmount",
            "baseName": "min_amount",
            "type": "number"
        },
        {
            "name": "paymentMethod",
            "baseName": "payment_method",
            "type": "OfferValidationsPaymentMethod"
        },
        {
            "name": "maxAllowed",
            "baseName": "max_allowed",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return OfferValidations.attributeTypeMap;
    }
}

