/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Offer Type Object
*/
export enum OfferType {
    Discount = <any> 'DISCOUNT',
    Cashback = <any> 'CASHBACK',
    DiscountAndCashback = <any> 'DISCOUNT_AND_CASHBACK',
    NoCostEmi = <any> 'NO_COST_EMI'
}
