/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-09-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OrderPayData } from './orderPayData';

/**
* Order Pay response once you create a transaction for that order
*/
export class OrderPayResponse {
    /**
    * total amount payable
    */
    'paymentAmount'?: number;
    /**
    * Payment identifier created by Cashfree
    */
    'cfPaymentId'?: number;
    /**
    * One of [\"upi\", \"netbanking\", \"card\", \"app\", \"cardless_emi\", \"paylater\", \"banktransfer\"] 
    */
    'paymentMethod'?: OrderPayResponse.PaymentMethodEnum;
    /**
    * One of [\"link\", \"collect\", \"qrcode\"]. In an older version we used to support different channels like \'gpay\', \'phonepe\' etc. However, we now support only the following channels - link, collect and qrcode. To process payments using gpay, you will have to provide channel as \'link\' and provider as \'gpay\'
    */
    'channel'?: OrderPayResponse.ChannelEnum;
    /**
    * One of [\"link\", \"custom\", \"form\"]
    */
    'action'?: OrderPayResponse.ActionEnum;
    'data'?: OrderPayData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "paymentAmount",
            "baseName": "payment_amount",
            "type": "number"
        },
        {
            "name": "cfPaymentId",
            "baseName": "cf_payment_id",
            "type": "number"
        },
        {
            "name": "paymentMethod",
            "baseName": "payment_method",
            "type": "OrderPayResponse.PaymentMethodEnum"
        },
        {
            "name": "channel",
            "baseName": "channel",
            "type": "OrderPayResponse.ChannelEnum"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "OrderPayResponse.ActionEnum"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "OrderPayData"
        }    ];

    static getAttributeTypeMap() {
        return OrderPayResponse.attributeTypeMap;
    }
}

export namespace OrderPayResponse {
    export enum PaymentMethodEnum {
        Netbanking = <any> 'netbanking',
        Card = <any> 'card',
        Upi = <any> 'upi',
        App = <any> 'app',
        CardlessEmi = <any> 'cardless_emi',
        Paylater = <any> 'paylater',
        Banktransfer = <any> 'banktransfer'
    }
    export enum ChannelEnum {
        Link = <any> 'link',
        Collect = <any> 'collect',
        Qrcode = <any> 'qrcode',
        Post = <any> 'post'
    }
    export enum ActionEnum {
        Link = <any> 'link',
        Custom = <any> 'custom',
        Form = <any> 'form',
        Post = <any> 'post'
    }
}
