/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { App } from './app';
import { AppPaymentMethod } from './appPaymentMethod';
import { Card } from './card';
import { CardEMI } from './cardEMI';
import { CardEMIPaymentMethod } from './cardEMIPaymentMethod';
import { CardPaymentMethod } from './cardPaymentMethod';
import { CardlessEMI } from './cardlessEMI';
import { CardlessEMIPaymentMethod } from './cardlessEMIPaymentMethod';
import { NetBankingPaymentMethod } from './netBankingPaymentMethod';
import { Netbanking } from './netbanking';
import { Paylater } from './paylater';
import { PaylaterPaymentMethod } from './paylaterPaymentMethod';
import { UPIPaymentMethod } from './uPIPaymentMethod';
import { Upi } from './upi';

export class OrderPayRequestPaymentMethod {
    'card': Card;
    'upi': Upi;
    'netbanking': Netbanking | null;
    'app': App;
    'emi': CardEMI;
    'cardlessEmi'?: CardlessEMI;
    'paylater'?: Paylater;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "card",
            "baseName": "card",
            "type": "Card"
        },
        {
            "name": "upi",
            "baseName": "upi",
            "type": "Upi"
        },
        {
            "name": "netbanking",
            "baseName": "netbanking",
            "type": "Netbanking"
        },
        {
            "name": "app",
            "baseName": "app",
            "type": "App"
        },
        {
            "name": "emi",
            "baseName": "emi",
            "type": "CardEMI"
        },
        {
            "name": "cardlessEmi",
            "baseName": "cardless_emi",
            "type": "CardlessEMI"
        },
        {
            "name": "paylater",
            "baseName": "paylater",
            "type": "Paylater"
        }    ];

    static getAttributeTypeMap() {
        return OrderPayRequestPaymentMethod.attributeTypeMap;
    }
}

