/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* OTP to be submitted for headless/native OTP
*/
export class OTPRequest {
    /**
    * OTP to be submitted
    */
    'otp': string;
    /**
    * The action for this workflow. Could be either SUBMIT_OTP or RESEND_OTP
    */
    'action': OTPRequest.ActionEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "otp",
            "baseName": "otp",
            "type": "string"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "OTPRequest.ActionEnum"
        }    ];

    static getAttributeTypeMap() {
        return OTPRequest.attributeTypeMap;
    }
}

export namespace OTPRequest {
    export enum ActionEnum {
        SubmitOtp = <any> 'SUBMIT_OTP',
        ResendOtp = <any> 'RESEND_OTP'
    }
}
