/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-09-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* This is the response shared when merchant inovkes the OTP submit or resend API
*/
export class OTPResponseEntity {
    /**
    * The payment id for which this request was sent
    */
    'cfPaymentId'?: number;
    /**
    * The action that was invoked for this request.
    */
    'action'?: OTPResponseEntity.ActionEnum;
    /**
    * Status of the is action. Will be either failed or successful. If the action is successful, you should still call the authorization status to verify the final payment status.
    */
    'authenticateStatus'?: OTPResponseEntity.AuthenticateStatusEnum;
    /**
    * Human readable message which describes the status in more detail
    */
    'paymentMessage'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cfPaymentId",
            "baseName": "cf_payment_id",
            "type": "number"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "OTPResponseEntity.ActionEnum"
        },
        {
            "name": "authenticateStatus",
            "baseName": "authenticate_status",
            "type": "OTPResponseEntity.AuthenticateStatusEnum"
        },
        {
            "name": "paymentMessage",
            "baseName": "payment_message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OTPResponseEntity.attributeTypeMap;
    }
}

export namespace OTPResponseEntity {
    export enum ActionEnum {
        SubmitOtp = <any> 'SUBMIT_OTP',
        ResendOtp = <any> 'RESEND_OTP'
    }
    export enum AuthenticateStatusEnum {
        Failed = <any> 'FAILED',
        Success = <any> 'SUCCESS'
    }
}
