/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AuthorizationInPaymentsEntity } from './authorizationInPaymentsEntity';
import { ErrorDetailsInPaymentsEntity } from './errorDetailsInPaymentsEntity';
import { PaymentMethodInPaymentsEntity } from './paymentMethodInPaymentsEntity';

/**
* payment entity full object
*/
export class PaymentsEntity {
    'cfPaymentId'?: number;
    'orderId'?: string;
    'entity'?: string;
    'errorDetails'?: ErrorDetailsInPaymentsEntity;
    'isCaptured'?: boolean;
    /**
    * Order amount can be different from payment amount if you collect service fee from the customer
    */
    'orderAmount'?: number;
    /**
    * Type of payment group. One of [\'upi\', \'card\', \'app\', \'netbanking\', \'paylater\', \'cardless_emi\']
    */
    'paymentGroup'?: string;
    'paymentCurrency'?: string;
    'paymentAmount'?: number;
    /**
    * This is the time when the payment was initiated
    */
    'paymentTime'?: string;
    /**
    * This is the time when the payment reaches its terminal state
    */
    'paymentCompletionTime'?: string;
    /**
    * The transaction status can be one of  [\"SUCCESS\", \"NOT_ATTEMPTED\", \"FAILED\", \"USER_DROPPED\", \"VOID\", \"CANCELLED\", \"PENDING\"]
    */
    'paymentStatus'?: PaymentsEntity.PaymentStatusEnum;
    'paymentMessage'?: string;
    'bankReference'?: string;
    'authId'?: string;
    'authorization'?: AuthorizationInPaymentsEntity | null;
    'paymentMethod'?: PaymentMethodInPaymentsEntity;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cfPaymentId",
            "baseName": "cf_payment_id",
            "type": "number"
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string"
        },
        {
            "name": "entity",
            "baseName": "entity",
            "type": "string"
        },
        {
            "name": "errorDetails",
            "baseName": "error_details",
            "type": "ErrorDetailsInPaymentsEntity"
        },
        {
            "name": "isCaptured",
            "baseName": "is_captured",
            "type": "boolean"
        },
        {
            "name": "orderAmount",
            "baseName": "order_amount",
            "type": "number"
        },
        {
            "name": "paymentGroup",
            "baseName": "payment_group",
            "type": "string"
        },
        {
            "name": "paymentCurrency",
            "baseName": "payment_currency",
            "type": "string"
        },
        {
            "name": "paymentAmount",
            "baseName": "payment_amount",
            "type": "number"
        },
        {
            "name": "paymentTime",
            "baseName": "payment_time",
            "type": "string"
        },
        {
            "name": "paymentCompletionTime",
            "baseName": "payment_completion_time",
            "type": "string"
        },
        {
            "name": "paymentStatus",
            "baseName": "payment_status",
            "type": "PaymentsEntity.PaymentStatusEnum"
        },
        {
            "name": "paymentMessage",
            "baseName": "payment_message",
            "type": "string"
        },
        {
            "name": "bankReference",
            "baseName": "bank_reference",
            "type": "string"
        },
        {
            "name": "authId",
            "baseName": "auth_id",
            "type": "string"
        },
        {
            "name": "authorization",
            "baseName": "authorization",
            "type": "AuthorizationInPaymentsEntity"
        },
        {
            "name": "paymentMethod",
            "baseName": "payment_method",
            "type": "PaymentMethodInPaymentsEntity"
        }    ];

    static getAttributeTypeMap() {
        return PaymentsEntity.attributeTypeMap;
    }
}

export namespace PaymentsEntity {
    export enum PaymentStatusEnum {
        Success = <any> 'SUCCESS',
        NotAttempted = <any> 'NOT_ATTEMPTED',
        Failed = <any> 'FAILED',
        UserDropped = <any> 'USER_DROPPED',
        Void = <any> 'VOID',
        Cancelled = <any> 'CANCELLED',
        Pending = <any> 'PENDING'
    }
}
