/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Error when rate limit is breached for your api
*/
export class RateLimitError {
    'message'?: string;
    'code'?: string;
    /**
    * rate_limit_error
    */
    'type'?: RateLimitError.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "RateLimitError.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return RateLimitError.attributeTypeMap;
    }
}

export namespace RateLimitError {
    export enum TypeEnum {
        RateLimitError = <any> 'rate_limit_error'
    }
}
