/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Card instrument meta information
*/
export class SavedInstrumentMeta {
    /**
    * card scheme/network of the saved card. Example visa, mastercard
    */
    'cardNetwork'?: string;
    /**
    * Issuing bank name of saved card
    */
    'cardBankName'?: string;
    /**
    * Issuing country of saved card
    */
    'cardCountry'?: string;
    /**
    * Type of saved card
    */
    'cardType'?: string;
    'cardTokenDetails'?: object | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cardNetwork",
            "baseName": "card_network",
            "type": "string"
        },
        {
            "name": "cardBankName",
            "baseName": "card_bank_name",
            "type": "string"
        },
        {
            "name": "cardCountry",
            "baseName": "card_country",
            "type": "string"
        },
        {
            "name": "cardType",
            "baseName": "card_type",
            "type": "string"
        },
        {
            "name": "cardTokenDetails",
            "baseName": "card_token_details",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return SavedInstrumentMeta.attributeTypeMap;
    }
}

