/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Create terminal response object
*/
export class TerminalResponse {
    'addedOn'?: string;
    'cfTerminalId'?: number;
    'lastUpdatedOn'?: string;
    'terminalArea'?: string;
    'teminalId'?: string;
    'terminalName'?: string;
    'terminalNote'?: string;
    'terminalPhoneNo'?: string;
    'terminalStatus'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addedOn",
            "baseName": "added_on",
            "type": "string"
        },
        {
            "name": "cfTerminalId",
            "baseName": "cf_terminal_id",
            "type": "number"
        },
        {
            "name": "lastUpdatedOn",
            "baseName": "last_updated_on",
            "type": "string"
        },
        {
            "name": "terminalArea",
            "baseName": "terminal_area",
            "type": "string"
        },
        {
            "name": "teminalId",
            "baseName": "teminal_id",
            "type": "string"
        },
        {
            "name": "terminalName",
            "baseName": "terminal_name",
            "type": "string"
        },
        {
            "name": "terminalNote",
            "baseName": "terminal_note",
            "type": "string"
        },
        {
            "name": "terminalPhoneNo",
            "baseName": "terminal_phone_no",
            "type": "string"
        },
        {
            "name": "terminalStatus",
            "baseName": "terminal_status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TerminalResponse.attributeTypeMap;
    }
}

