/**
 * Cashfree Payment Gateway APIs
 * Cashfree\'s Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UPIAuthorizeDetails } from './uPIAuthorizeDetails';

/**
* UPI collect payment method object
*/
export class Upi {
    /**
    * Specify the channel through which the payment must be processed. Can be one of [\"link\", \"collect\", \"qrcode\"]
    */
    'channel': Upi.ChannelEnum;
    /**
    * Customer UPI VPA to process payment.  ### Important This is a required parameter for channel = `collect` 
    */
    'upiId'?: string;
    /**
    * use this if you want cashfree to show a loader. Sample response below. It is only supported for collect `action:collect` will be returned with `data.url` having the link for redirection 
    */
    'upiRedirectUrl'?: boolean;
    /**
    * The UPI request will be valid for this expiry minutes. This parameter is only applicable for a UPI collect payment. The default value is 5 minutes. You should keep the minimum as 5 minutes, and maximum as 15 minutes
    */
    'upiExpiryMinutes'?: number;
    /**
    * For one time mandate on UPI. Set this as authorize_only = true. Please note that you can only use the \"collect\" channel if you are sending a one time mandate request
    */
    'authorizeOnly'?: boolean;
    'authorization'?: UPIAuthorizeDetails;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channel",
            "baseName": "channel",
            "type": "Upi.ChannelEnum"
        },
        {
            "name": "upiId",
            "baseName": "upi_id",
            "type": "string"
        },
        {
            "name": "upiRedirectUrl",
            "baseName": "upi_redirect_url",
            "type": "boolean"
        },
        {
            "name": "upiExpiryMinutes",
            "baseName": "upi_expiry_minutes",
            "type": "number"
        },
        {
            "name": "authorizeOnly",
            "baseName": "authorize_only",
            "type": "boolean"
        },
        {
            "name": "authorization",
            "baseName": "authorization",
            "type": "UPIAuthorizeDetails"
        }    ];

    static getAttributeTypeMap() {
        return Upi.attributeTypeMap;
    }
}

export namespace Upi {
    export enum ChannelEnum {
        Link = <any> 'link',
        Collect = <any> 'collect',
        Qrcode = <any> 'qrcode'
    }
}
